export enum StudyType {
	PAPANICOLAOU = 'PAPANICOLAOU',
	VAGINAL_CULTURE = 'VAGINAL_CULTURE',
	VPH = 'VPH',
	TRANSVAGINAL_ULTRASOUND = 'TRANSVAGINAL_ULTRASOUND',
	DENSITOMETRY = 'DENSITOMETRY',
	TOMOGRAPHY = 'TOMOGRAPHY',
	MRI = 'MRI',
	LABORATORY = 'LABORATORY',
	ULTRASOUND = 'ULTRASOUND',
	MASTOGRAPHY = 'MASTOGRAPHY',
}

export enum TriagePriority {
	URGENCY = 1,
	APPOINTMENT = 2,
	WALK_IN = 3,
}

export enum VisitType {
	SCHEDULED = 'SCHEDULED',
	WALK_IN = 'WALK_IN',
}

export enum StudyStatus {
	PENDING = 'PENDING',
	QUEUED = 'QUEUED',
	BLOCKED = 'BLOCKED',
	IN_PROGRESS = 'IN_PROGRESS',
	COMPLETED = 'COMPLETED',
	SKIPPED = 'SKIPPED',
}
