// AUTO-GENERADO desde documentos/servicios salud digna.xlsx
// + extensiones MVP. Usado por prisma/seed.ts

export interface SeedCategoria {
  id: number;
  nombre: string;
  tiempoServicioMin: number;
  tiempoEsperaPromedioMin: number;
  items: Array<{ nombre: string; precio: number | null }>;
}

export const SEED_CATALOGO: SeedCategoria[] = [
  {
    id: 2,
    nombre: 'LABORATORIO',
    tiempoServicioMin: 5,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Paquete anticuerpos anti sarampion igg e igm', precio: 390.0 },
      { nombre: 'Paquete anticuerpos anti sarampion igm', precio: 220.0 },
      { nombre: 'Paquete anticuerpos anti sarampion igg', precio: 220.0 },
      { nombre: 'Paquete embarazo sano TRIM I', precio: 475.0 },
      { nombre: 'Paquete completo adulto', precio: 460.0 },
      { nombre: 'Paquete diabetico', precio: 215.0 },
      { nombre: 'Paquete perfil de lipidos', precio: 230.0 },
      { nombre: 'Paquete perfil electrolitos 3 parametros', precio: 180.0 },
      { nombre: 'Paquete perfil electrolitos 6 parametros', precio: 340.0 },
      { nombre: 'Paquete perfil ginecologico', precio: 595.0 },
      { nombre: 'Paquete perfil tiroideo completo', precio: 560.0 },
      { nombre: 'Paquete prenupciales con vih', precio: 305.0 },
      { nombre: 'Paquete preoperatorios', precio: 335.0 },
      { nombre: 'Paquete prueba de funcionamiento hepático', precio: 315.0 },
      { nombre: 'Paquete qs6 parámetros', precio: 195.0 },
      { nombre: 'Paquete qs3 glucosa-colesterol-triglicéridos', precio: 100.0 },
      { nombre: 'Paquete qs3 glucosa-urea-creatinina', precio: 105.0 },
      { nombre: 'Paquete perfil antidoping 3', precio: 225.0 },
      { nombre: 'Química sanguínea 30 parámetros', precio: 375.0 },
      { nombre: 'Paquete embarazo sano TRIM II y III', precio: 475.0 },
      { nombre: 'Paquete básico adulto', precio: 285.0 },
      { nombre: 'Paquete embarazo sano ultrasonido 4D', precio: 485.0 },
      { nombre: 'Paquete perfil reumático', precio: 285.0 },
      { nombre: 'Paquete infantil', precio: 195.0 },
      { nombre: 'Paquete coproparasitoscópico 2 muestras', precio: 75.0 },
      { nombre: 'Paquete coproparasitoscópico 3 muestras', precio: 120.0 },
      { nombre: 'Paquete depuración de creatinina', precio: 95.0 },
      { nombre: 'Seguimiento integral covid-19', precio: 540.0 },
      { nombre: 'Paquete tiroideo', precio: 815.0 },
      { nombre: 'Paquete prostático', precio: 475.0 },
      { nombre: 'Paquete salud integral', precio: 635.0 },
      { nombre: 'Paquete aviación - inicial', precio: 1206.0 },
      { nombre: 'Paquete aviación - renovación', precio: 1026.0 },
      { nombre: 'Paquete embarazo sano TRIM I sin asesoría', precio: 465.0 },
      { nombre: 'Paquete embarazo sano TRIM II y III sin asesoría', precio: 465.0 },
      { nombre: 'Paquete embarazo sano ultrasonido 4D sin asesoría', precio: 470.0 },
      { nombre: 'Paquete perfil antidoping 6', precio: 285.0 },
      { nombre: 'Paquete lupus hibrido', precio: 1000.0 },
      { nombre: 'Perfil de torch 1 (inmunoglobulinas tipo m)', precio: 900.0 },
      { nombre: 'Perfil de torch 2 (inmunoglobulinas tipo g)', precio: 950.0 },
      { nombre: 'Perfil de torch 3 (inmunoglobulinas g y m)', precio: 1800.0 },
      { nombre: 'Paquete ginecológico completo', precio: 850.0 },
      { nombre: 'Paquete salud mujer', precio: 590.0 },
      { nombre: 'Paquete péptido c, curva de 2 muestras', precio: 500.0 },
      { nombre: 'Paquete curva de cortisol a 2 muestras', precio: 220.0 },
      { nombre: 'Anticuerpos anti treponema pallidum igg e igm', precio: 500.0 },
      { nombre: 'Paquete perfil de hierro', precio: 280.0 },
      { nombre: 'Paquete curva de prolactina a 2 muestras', precio: 220.0 },
      { nombre: 'Paquete curva de tolerancia a la insulina:', precio: 415.0 },
      { nombre: 'Paquete curva de tolerancia a la insulina 5 hrs', precio: 570.0 },
      { nombre: 'Paquete curva de tolerancia a la insulina cada 30', precio: 522.0 },
      { nombre: 'Paquete panel de hepatitis a b c', precio: 1505.0 },
      { nombre: 'Paquete insulina pre y postpandrial', precio: 385.0 },
      { nombre: 'Paquete perfil de hepatitis b', precio: 1438.0 },
      { nombre: 'Paquete perfil de hepatitis b (crónica)', precio: 1370.0 },
      { nombre: 'Paquete perfil de alérgenos alimenticios', precio: 2413.0 },
      { nombre: 'Paquete perfil de alérgenos inhalatorios', precio: 2413.0 },
    ],
  },
  {
    id: 4,
    nombre: 'PAPANICOLAOU',
    tiempoServicioMin: 8,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Paquete papanicolaou+vph por pcr', precio: 335.0 },
      { nombre: 'Paquete ginecologico completo', precio: 850.0 },
      { nombre: 'Paquete salud mujer', precio: 590.0 },
      { nombre: 'Paquete integral mujer', precio: 630.0 },
      { nombre: 'Paquete prevencion femenina', precio: 530.0 },
    ],
  },
  {
    id: 5,
    nombre: 'RAYOS X',
    tiempoServicioMin: 10,
    tiempoEsperaPromedioMin: 30,
    items: [
      { nombre: 'Paquete aviacion - inicial', precio: 1206.0 },
      { nombre: 'Mano ap', precio: 215.0 },
      { nombre: 'Abdomen ap de pie', precio: 215.0 },
      { nombre: 'Abdomen ap en decubito', precio: 360.0 },
      { nombre: 'Abdomen de pie y decubito', precio: 225.0 },
      { nombre: 'Abdomen lateral', precio: 215.0 },
      { nombre: 'Antebrazo cubito y radio ap', precio: 275.0 },
      { nombre: 'Antebrazo ap comparativo', precio: 285.0 },
      { nombre: 'Antebrazo ap y lateral', precio: 530.0 },
      { nombre: 'Antebrazo ap y lateral comparativo', precio: 225.0 },
      { nombre: 'Brazo humero ap', precio: 225.0 },
      { nombre: 'Brazo lateral', precio: 360.0 },
      { nombre: 'Brazo ap comparativo', precio: 360.0 },
      { nombre: 'Brazo ap y lateral', precio: 360.0 },
      { nombre: 'Brazo ap y lateral comparativo', precio: 660.0 },
      { nombre: 'Calcaneo talon axial', precio: 225.0 },
      { nombre: 'Calcaneo lateral', precio: 215.0 },
      { nombre: 'Calcaneo axial comparativo', precio: 300.0 },
      { nombre: 'Calcaneo lateral comparativo', precio: 285.0 },
      { nombre: 'Cefalopelvimetria', precio: 525.0 },
      { nombre: 'Cefalopelvimetria', precio: 525.0 },
      { nombre: 'Clavicula ap', precio: 215.0 },
      { nombre: 'Clavicula oblicua', precio: 225.0 },
      { nombre: 'Clavicula ap y oblicua', precio: 360.0 },
      { nombre: 'Clavicula ap comparativo', precio: 380.0 },
      { nombre: 'Clavicula oblicua comparativo', precio: 350.0 },
      { nombre: 'Codo ap', precio: 225.0 },
      { nombre: 'Codo ap y lateral', precio: 295.0 },
      { nombre: 'Codo oblicua -rotacion interna y externa-', precio: 290.0 },
      { nombre: 'Codo ap lateral y oblicua', precio: 435.0 },
      { nombre: 'Codo ap y lateral comparativo', precio: 550.0 },
      { nombre: 'Columna cervical cuello ap', precio: 215.0 },
      { nombre: 'Columna cervical cuello lateral', precio: 215.0 },
      { nombre: 'Columna cervical ap y lateral', precio: 350.0 },
      { nombre: 'Columna cervical ap transoral', precio: 215.0 },
      { nombre: 'Columna cervical dinamica -flex. y ext-', precio: 360.0 },
      { nombre: 'Columna cervical oblicuas', precio: 360.0 },
      { nombre: 'Columna cervical ap- lateral y oblicuas', precio: 650.0 },
      { nombre: 'Columna cervical ap- lateral- oblicuas y dinamicas', precio: 1000.0 },
      { nombre: 'Columna cervical ap- lateral y dinamicas', precio: 730.0 },
      { nombre: 'Columna dorsal ap', precio: 215.0 },
      { nombre: 'Columnda dorsal lateral', precio: 215.0 },
      { nombre: 'Columnda dorsal ap y lateral', precio: 360.0 },
      { nombre: 'Columnda dorsal oblicuas', precio: 360.0 },
      { nombre: 'Columna dorsal ap lateral y oblicuas', precio: 650.0 },
      { nombre: 'Columna lumbar ap', precio: 215.0 },
      { nombre: 'Columna lumbar lateral', precio: 215.0 },
      { nombre: 'Columna lumbar ap y lateral', precio: 340.0 },
      { nombre: 'Columna lumbosacra oblicuas', precio: 360.0 },
      { nombre: 'Columna lumbosacra ap- lateral y oblicuas', precio: 690.0 },
      { nombre: 'Columna lumbosacra dinamicas -flexion y extension-', precio: 360.0 },
      { nombre: 'Columna lumbosacra ap lateral oblicuas y dinamicas', precio: 1010.0 },
      { nombre: 'Columna sacrocoxigea ap', precio: 225.0 },
      { nombre: 'Columna sacrocoxigea lateral', precio: 225.0 },
      { nombre: 'Columna sacrocoxigea ap y lateral', precio: 360.0 },
      { nombre: 'Columna cervical y dorsal ap y lateral', precio: 665.0 },
      { nombre: 'Columna cervical y lumbar ap y lateral', precio: 680.0 },
      { nombre: 'Columna cervical- dorsal y lumbar ap y lateral', precio: 980.0 },
      { nombre: 'Columna cervical y lumbar ap- lateral y oblicuas', precio: 1240.0 },
      { nombre: 'Columna cervical y lumbar ap- lateral y dinamicas', precio: 1240.0 },
      { nombre: 'Craneo ap', precio: 215.0 },
      { nombre: 'Craneo lateral', precio: 215.0 },
      { nombre: 'Craneo ap y lateral', precio: 360.0 },
      { nombre: 'Craneo hirtz (base del craneo)', precio: 235.0 },
      { nombre: 'Craneo oblicua', precio: 235.0 },
      { nombre: 'Craneo ap lateral y towne', precio: 525.0 },
      { nombre: 'Craneo towne', precio: 215.0 },
      { nombre: 'Escanometria (medición radiológica de miembros inferiores)', precio: 475.0 },
      { nombre: 'Escapula ap', precio: 225.0 },
      { nombre: 'Escapula oblicua', precio: 235.0 },
      { nombre: 'Escapula ap y oblicua', precio: 365.0 },
      { nombre: 'Escapula tangencial', precio: 235.0 },
      { nombre: 'Escapula ap comparativo', precio: 380.0 },
      { nombre: 'Femur -muslo- ap', precio: 215.0 },
      { nombre: 'Femur lateral', precio: 215.0 },
      { nombre: 'Femur ap y lateral', precio: 360.0 },
      { nombre: 'Femur ap comparativo', precio: 360.0 },
      { nombre: 'Femur lateral comparativo', precio: 380.0 },
      { nombre: 'Femur ap y lateral comparativo', precio: 610.0 },
      { nombre: 'Hombro 3 posiciones (ap rot ext y rot int)', precio: 505.0 },
      { nombre: 'Hombro ap', precio: 195.0 },
      { nombre: 'Hombro oblicua', precio: 225.0 },
      { nombre: 'Hombro ap y oblicua', precio: 360.0 },
      { nombre: 'Hombro ap comparativo', precio: 360.0 },
      { nombre: 'Hombro ap y oblicua comparativo', precio: 625.0 },
      { nombre: 'Mandibula ap', precio: 235.0 },
      { nombre: 'Mandibula lateral', precio: 235.0 },
      { nombre: 'Mandibula ap y lateral', precio: 365.0 },
      { nombre: 'Mandibula oblicua', precio: 235.0 },
      { nombre: 'Mandibula ap y oblicua', precio: 365.0 },
      { nombre: 'Mandibula oblicuas -izq y der-', precio: 330.0 },
      { nombre: 'Mandibula ap y oblicua', precio: 295.0 },
      { nombre: 'Mano ap y lateral', precio: 295.0 },
      { nombre: 'Mano lateral', precio: 225.0 },
      { nombre: 'Mano ap y oblicua comparativo', precio: 520.0 },
      { nombre: 'Mano ap y lateral comparativo', precio: 465.0 },
      { nombre: 'Mano ap -lateral y oblicua', precio: 455.0 },
      { nombre: 'Muñeca ap', precio: 215.0 },
      { nombre: 'Muñeca lateral', precio: 215.0 },
      { nombre: 'Muñeca ap y lateral', precio: 295.0 },
      { nombre: 'Muñeca ap- lateral y oblicua', precio: 430.0 },
      { nombre: 'Muñeca con rot ext y rot int -para escafoides-', precio: 300.0 },
      { nombre: 'Muñeca oblicua int y ext', precio: 280.0 },
      { nombre: 'Muñeca tunel del carpo', precio: 225.0 },
      { nombre: 'Pelvis cadera ap art. Coxofemorales', precio: 225.0 },
      { nombre: 'Pelvis -cadera lateral', precio: 205.0 },
      { nombre: 'Pelvis cadera oblicua', precio: 220.0 },
      { nombre: 'Pelvis cadera ap y lateral', precio: 380.0 },
      { nombre: 'Pelvis ap -cadera- y oblicua', precio: 370.0 },
      { nombre: 'Pelvis ap posición de rana', precio: 220.0 },
      { nombre: 'Pelvis oblicuas comparativo', precio: 360.0 },
      { nombre: 'Pelvis ap y lateral u oblicuas comparativo', precio: 360.0 },
      { nombre: 'Perfilograma', precio: 545.0 },
      { nombre: 'Pie ap -dorso plantar', precio: 215.0 },
      { nombre: 'Pie lateral', precio: 215.0 },
      { nombre: 'Pie ap y lateral', precio: 215.0 },
      { nombre: 'Pie ap y oblicua', precio: 295.0 },
      { nombre: 'Pie lateral comparativo', precio: 295.0 },
      { nombre: 'Pie ap y lateral comparativo', precio: 290.0 },
      { nombre: 'Pie ap y oblicua comparativo', precio: 455.0 },
      { nombre: 'Pierna -tibia y perone- ap', precio: 215.0 },
      { nombre: 'Pierna lateral', precio: 215.0 },
      { nombre: 'Pierna ap y lateral', precio: 295.0 },
      { nombre: 'Pierna ap y lateral comparativo', precio: 540.0 },
      { nombre: 'Rodilla ap', precio: 215.0 },
      { nombre: 'Rodilla lateral', precio: 215.0 },
      { nombre: 'Rodilla oblicua', precio: 225.0 },
      { nombre: 'Rodilla ap y lateral', precio: 295.0 },
      { nombre: 'Rodilla ap y oblicua', precio: 285.0 },
      { nombre: 'Rodilla axial 30 grados -unilateral o bilateral-', precio: 505.0 },
      { nombre: 'Rodilla axial 60 grados -unilateral o bilateral-', precio: 370.0 },
      { nombre: 'Rodilla axial 90 grados -unilateral o bilateral-', precio: 1830.0 },
      { nombre: 'Rodilla axial 30 60 90 grados -unilat o bilat-', precio: 235.0 },
      { nombre: 'Rodilla ap y lateral comparativo', precio: 225.0 },
      { nombre: 'Schuller bilateral', precio: 370.0 },
      { nombre: 'Schuller unilateral', precio: 225.0 },
      { nombre: 'Senos paranasales caldwell', precio: 195.0 },
      { nombre: 'Senos paranasales lateral', precio: 215.0 },
      { nombre: 'Senos paranasales waters', precio: 215.0 },
      { nombre: 'Senos paranasales -caldwell-lateralwaters', precio: 505.0 },
      { nombre: 'Senos paranasales -waters- lateral', precio: 370.0 },
      { nombre: 'Serie osea metastasica', precio: 1830.0 },
      { nombre: 'Silla turca ap', precio: 235.0 },
      { nombre: 'Silla turca lateral', precio: 225.0 },
      { nombre: 'Silla turca ap y lateral', precio: 370.0 },
      { nombre: 'Apicograma', precio: 225.0 },
      { nombre: 'Teleradiografia de torax pa', precio: 195.0 },
      { nombre: 'Torax lateral', precio: 215.0 },
      { nombre: 'Torax oblicua', precio: 215.0 },
      { nombre: 'Teleradiografia torax pa y lateral', precio: 360.0 },
      { nombre: 'Teleradiografia torax pa y oblicua', precio: 370.0 },
      { nombre: 'Torax pa y oblicuas (izq y der)', precio: 665.0 },
      { nombre: 'Torax pa y laterales (izq y der)', precio: 515.0 },
      { nombre: 'Torax oseo ap', precio: 215.0 },
      { nombre: 'Torax oseo lateral -esternon', precio: 225.0 },
      { nombre: 'Torax oseo oblicua -esternon', precio: 225.0 },
      { nombre: 'Torax oseo ap y lateral', precio: 370.0 },
      { nombre: 'Torax oseo ap y oblicua', precio: 360.0 },
      { nombre: 'Tobillo ap', precio: 215.0 },
      { nombre: 'Tobillo lateral', precio: 215.0 },
      { nombre: 'Tobillo ap y lateral', precio: 295.0 },
      { nombre: 'Tobillo oblicua', precio: 215.0 },
      { nombre: 'Tobillo ap y lateral comparativo', precio: 520.0 },
      { nombre: 'Tobillo lateral comparativo', precio: 290.0 },
      { nombre: 'Tobillo unilateral con stress', precio: 235.0 },
      { nombre: 'Orbitas ap', precio: 215.0 },
      { nombre: 'Orbita oblicua', precio: 235.0 },
      { nombre: 'Orbita ap y obl', precio: 380.0 },
      { nombre: 'Orbita ap y oblicuas', precio: 545.0 },
      { nombre: 'Rodilla ap comparativo', precio: 225.0 },
      { nombre: 'Senos paranasales --waters caldwell--', precio: 360.0 },
      { nombre: 'Rodilla ap y oblicua comparativo', precio: 435.0 },
      { nombre: 'Pie ap comparativo', precio: 225.0 },
      { nombre: 'Pie ap lateral y oblicua', precio: 455.0 },
      { nombre: 'Pie ap lateral y oblicua comparativo', precio: 625.0 },
      { nombre: 'Pierna ap comparativo', precio: 285.0 },
      { nombre: 'Pierna lateral comparativo', precio: 300.0 },
      { nombre: 'Rodilla ap lateral y oblicua', precio: 465.0 },
      { nombre: 'Rodilla lateral comparativo', precio: 285.0 },
      { nombre: 'Senos paranasales -caldwell lateral-', precio: 370.0 },
      { nombre: 'Abdomen ap de pie de cubito y lateral', precio: 510.0 },
      { nombre: 'Antebrazo ap lateral y oblicua', precio: 465.0 },
      { nombre: 'Antebrazo -cubito y radio- lateral', precio: 215.0 },
      { nombre: 'Antebrazo -cubito y radio- oblicua', precio: 225.0 },
      { nombre: 'Antebrazo lateral comparativo', precio: 305.0 },
      { nombre: 'Antebrazo oblicua comparativo', precio: 300.0 },
      { nombre: 'Torax oseo ap lateral y oblicua', precio: 530.0 },
      { nombre: 'Brazo lateral comparativo', precio: 370.0 },
      { nombre: 'Calcaneo axial y lateral comparativo', precio: 455.0 },
      { nombre: 'Calcaneo axial y lateral', precio: 360.0 },
      { nombre: 'Mano ap comparativo', precio: 285.0 },
      { nombre: 'Mano lateral comparativo', precio: 235.0 },
      { nombre: 'Mano oblicua comparativo', precio: 285.0 },
      { nombre: 'Clavicula ap y oblicua comparativo', precio: 595.0 },
      { nombre: 'Codo ap comparativo', precio: 300.0 },
      { nombre: 'Codo lateral comparativo', precio: 300.0 },
      { nombre: 'Tobillo ap comparativo', precio: 285.0 },
      { nombre: 'Tobillo ap lateral y oblicua', precio: 430.0 },
      { nombre: 'Tobillo ap lateral y oblicua comparativo', precio: 760.0 },
      { nombre: 'Tobillo ap y oblicua comparativo', precio: 540.0 },
      { nombre: 'Tobillo oblicua comparativo', precio: 285.0 },
      { nombre: 'Muñeca ap comparativo', precio: 300.0 },
      { nombre: 'Muñeca ap y lateral comparativo', precio: 465.0 },
      { nombre: 'Muñeca lateral comparativo', precio: 225.0 },
      { nombre: 'Pelvis lateral u oblicuas comparativo', precio: 360.0 },
      { nombre: 'Hombro 2 posiciones -rotacion interna y externa-', precio: 365.0 },
      { nombre: 'Columna lumbar ap lateral y dinamicas', precio: 690.0 },
      { nombre: 'Hombro oblicua comparativo', precio: 360.0 },
      { nombre: 'Abdomen ap y lateral', precio: 370.0 },
      { nombre: 'Codo lateral', precio: 225.0 },
      { nombre: 'Hombro transtoracico', precio: 215.0 },
      { nombre: 'Mano oblicua', precio: 215.0 },
      { nombre: 'Tobillo ap y oblicua', precio: 290.0 },
      { nombre: 'Muñeca ap y oblicua', precio: 290.0 },
    ],
  },
  {
    id: 6,
    nombre: 'ULTRASONIDO',
    tiempoServicioMin: 15,
    tiempoEsperaPromedioMin: 30,
    items: [
      { nombre: 'Ultrasonido abdominal', precio: 550.0 },
      { nombre: 'Ultrasonido pelvico', precio: 480.0 },
      { nombre: 'Ultrasonido obstetrico', precio: 620.0 },
      { nombre: 'Ultrasonido renal', precio: 530.0 },
      { nombre: 'Ultrasonido tiroideo', precio: 540.0 },
      { nombre: 'Ultrasonido mamario', precio: 520.0 },
      { nombre: 'Ultrasonido de hombro', precio: 500.0 },
      { nombre: 'Ultrasonido transvaginal', precio: 580.0 },
    ],
  },
  {
    id: 9,
    nombre: 'ELECTROCARDIOGRAMA',
    tiempoServicioMin: 7,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Mastografia + electro', precio: 365.0 },
      { nombre: 'Electrocardiograma', precio: 135.0 },
    ],
  },
  {
    id: 11,
    nombre: 'TOMOGRAFIA',
    tiempoServicioMin: 20,
    tiempoEsperaPromedioMin: 30,
    items: [
      { nombre: 'Tomografia simple de craneo', precio: 2200.0 },
      { nombre: 'Tomografia simple de torax', precio: 2400.0 },
      { nombre: 'Tomografia simple de abdomen', precio: 2600.0 },
      { nombre: 'Tomografia contrastada de abdomen', precio: 3500.0 },
      { nombre: 'Tomografia de columna cervical', precio: 2300.0 },
      { nombre: 'Tomografia de columna lumbar', precio: 2300.0 },
    ],
  },
  {
    id: 12,
    nombre: 'RESONANCIA MAGNETICA',
    tiempoServicioMin: 30,
    tiempoEsperaPromedioMin: 40,
    items: [
      { nombre: 'Resonancia de cerebro', precio: 4200.0 },
      { nombre: 'Resonancia de columna cervical', precio: 4200.0 },
      { nombre: 'Resonancia de columna lumbar', precio: 4200.0 },
      { nombre: 'Resonancia de rodilla', precio: 4000.0 },
      { nombre: 'Resonancia de hombro', precio: 4000.0 },
      { nombre: 'Resonancia de abdomen', precio: 4500.0 },
    ],
  },
  {
    id: 16,
    nombre: 'NUTRICION',
    tiempoServicioMin: 15,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Paquete embarazo sano TRIM I', precio: 475.0 },
      { nombre: 'Paquete embarazo sano TRIM II y III', precio: 475.0 },
      { nombre: 'Paquete embarazo sano ultrasonido 4D', precio: 485.0 },
      { nombre: 'Consulta nutricional', precio: 60.0 },
    ],
  },
  {
    id: 3,
    nombre: 'MASTOGRAFIA',
    tiempoServicioMin: 8,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Mastografia bilateral', precio: 695.0 },
      { nombre: 'Mastografia + densitometria', precio: 335.0 },
      { nombre: 'Mastografia + electrocardiograma', precio: 365.0 },
      { nombre: 'Tomosintesis', precio: 550.0 },
      { nombre: 'Mastografia contrastada', precio: 2500.0 },
    ],
  },
  {
    id: 1,
    nombre: 'DENSITOMETRIA',
    tiempoServicioMin: 12,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Mastografia + densitometria', precio: 335.0 },
      { nombre: 'Paquete integral mujer', precio: 630.0 },
      { nombre: 'Densitometria osea de columna y femur', precio: 85.0 },
      { nombre: 'Densitometria pediatrica de columna y cuerpo compl', precio: 250.0 },
      { nombre: 'Densitometria ósea de cuerpo completo', precio: 250.0 },
      { nombre: 'Mastografía', precio: null },
      { nombre: 'Mastografia + densitometria', precio: 335.0 },
      { nombre: 'Mastografia + electro', precio: 365.0 },
      { nombre: 'Paquete integral mujer', precio: 630.0 },
      { nombre: 'Mastografia', precio: 295.0 },
      { nombre: 'Tomosíntesis', precio: 550.002 },
      { nombre: 'Mastografía contrastada', precio: 2499.997 },
    ],
  },
  {
    id: 38,
    nombre: 'OPTICA',
    tiempoServicioMin: 12,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Examen visual completo', precio: 150.0 },
      { nombre: 'Lentes de contacto - adaptacion', precio: 350.0 },
      { nombre: 'Examen visual ninos', precio: 150.0 },
      { nombre: 'Cambio de graduacion', precio: 100.0 },
    ],
  },
  {
    id: 52,
    nombre: 'CONSULTA GENERAL',
    tiempoServicioMin: 15,
    tiempoEsperaPromedioMin: 20,
    items: [
      { nombre: 'Consulta medica general', precio: 130.0 },
      { nombre: 'Consulta de seguimiento', precio: 100.0 },
      { nombre: 'Certificado medico', precio: 130.0 },
      { nombre: 'Consulta nutricional', precio: 150.0 },
    ],
  },
];
